# Generated by Django 3.0 on 2025-03-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='COACH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added', to='myapp.Login'),
        ),
    ]
