# Generated by Django 3.0 on 2025-03-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250307_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='file',
            field=models.CharField(max_length=1000),
        ),
    ]
