# Generated by Django 3.0 on 2025-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250315_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
