# Generated by Django 3.0 on 2025-03-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250315_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='GAME',
        ),
    ]
