# Generated by Django 3.0 on 2025-03-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_video_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial_request',
            old_name='TRAIL',
            new_name='TRAILS',
        ),
    ]
