# Generated by Django 3.0 on 2025-03-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250320_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial_request',
            old_name='TRAILS',
            new_name='TRIALS',
        ),
    ]
